spring.application.name=SpringActuator

management.endpoints.web.exposure.include=health,info,metrics

management.info.env.enabled=true
info.app.name=Actuator Demo App
info.app.version=1.0
info.app.description=simple actuator demo app
